# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-20 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions_dashboard', '0002_auto_20190918_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='technician',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
